/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
import com.itextpdf.text.Element;
import com.itextpdf.text.Font;
import com.itextpdf.text.Image;
import com.itextpdf.text.Paragraph;
import com.itextpdf.text.pdf.PdfPCell;
import com.itextpdf.text.pdf.PdfPTable;
import com.itextpdf.text.pdf.PdfWriter;
import java.io.File;
import java.io.FileOutputStream;
import java.sql.*;
import project.*;
import java.sql.ResultSet;
import java.text.SimpleDateFormat;
import java.util.Calendar;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
 
/**
 *
 * @author Python-workspace
 */
public class checkout extends javax.swing.JFrame {

    /**
     * Creates new form checkout
     */
    public checkout() {
        initComponents();
        jTextField2.setEditable(false);
        jTextField3.setEditable(false);
        jTextField4.setEditable(false);
        jTextField5.setEditable(false);
        jTextField6.setEditable(false);
        jTextField7.setEditable(false);
        jTextField8.setEditable(false);
        jTextField9.setEditable(false);
    }
    int get_id=0;
    String Query,roomtype,bed,roomno,address,member,totamt;
    double gst = 0.0;
    
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel2 = new javax.swing.JPanel();
        jButton5 = new javax.swing.JButton();
        jLabel17 = new javax.swing.JLabel();
        jButton4 = new javax.swing.JButton();
        jLabel16 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();
        jTextField1 = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jTextField2 = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jTextField3 = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jTextField4 = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        jTextField5 = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jTextField6 = new javax.swing.JTextField();
        jTextField7 = new javax.swing.JTextField();
        jTextField8 = new javax.swing.JTextField();
        jTextField9 = new javax.swing.JTextField();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        addComponentListener(new java.awt.event.ComponentAdapter() {
            public void componentShown(java.awt.event.ComponentEvent evt) {
                formComponentShown(evt);
            }
        });
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel2.setBackground(new java.awt.Color(255, 153, 153));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jButton5.setBackground(new java.awt.Color(34, 150, 94));
        jButton5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/icons8-back-30.png"))); // NOI18N
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });
        jPanel2.add(jButton5, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 11, 41, 39));

        jLabel17.setFont(new java.awt.Font("Monotype Corsiva", 1, 40)); // NOI18N
        jLabel17.setForeground(new java.awt.Color(255, 255, 255));
        jLabel17.setText("CHECK-OUT");
        jPanel2.add(jLabel17, new org.netbeans.lib.awtextra.AbsoluteConstraints(570, 70, 230, -1));

        jButton4.setBackground(new java.awt.Color(255, 44, 18));
        jButton4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/icons8-close-window-30.png"))); // NOI18N
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });
        jPanel2.add(jButton4, new org.netbeans.lib.awtextra.AbsoluteConstraints(1233, 10, 30, 30));

        jLabel16.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/tony-yakovlenko-lDxxeAJrWpE-unsplash.jpg"))); // NOI18N
        jLabel16.setText("jLabel16");
        jPanel2.add(jLabel16, new org.netbeans.lib.awtextra.AbsoluteConstraints(-80, 0, 1350, 160));

        getContentPane().add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1270, 160));

        jPanel1.setBackground(new java.awt.Color(33, 38, 40));

        jTable1.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N
        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "ID", "NAME", "MOBILE NO.", "COUNTRY", "EMAIL", "GENDER", "ID PROOF", "ID NUMBER", "ADDRESS", "TOTAL MEMBER", "CHECK-IN", "BEDS", "ROOM TYPE", "ROOM NO.", "MODE OF PAYMENT", "TARIFF / DAY"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jTable1.setShowGrid(true);
        jTable1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTable1MouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(jTable1);

        jLabel1.setFont(new java.awt.Font("Myanmar Text", 1, 14)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(188, 211, 13));
        jLabel1.setText("ROOM NO");

        jTextField1.setFont(new java.awt.Font("Nirmala UI Semilight", 1, 13)); // NOI18N

        jButton1.setBackground(new java.awt.Color(84, 159, 232));
        jButton1.setFont(new java.awt.Font("Myanmar Text", 1, 12)); // NOI18N
        jButton1.setForeground(new java.awt.Color(31, 24, 27));
        jButton1.setText("SEARCH");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jLabel2.setFont(new java.awt.Font("Myanmar Text", 1, 13)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(188, 211, 13));
        jLabel2.setText("CUSTOMER NAME");

        jTextField2.setFont(new java.awt.Font("Nirmala UI Semilight", 1, 13)); // NOI18N

        jLabel3.setFont(new java.awt.Font("Myanmar Text", 1, 13)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(188, 211, 13));
        jLabel3.setText("CHECK-IN DATE ");

        jTextField3.setFont(new java.awt.Font("Nirmala UI Semilight", 1, 13)); // NOI18N

        jLabel4.setFont(new java.awt.Font("Myanmar Text", 1, 13)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(188, 211, 13));
        jLabel4.setText("CHECK-OUT ");

        jTextField4.setFont(new java.awt.Font("Nirmala UI Semilight", 1, 13)); // NOI18N

        jLabel5.setFont(new java.awt.Font("Myanmar Text", 1, 13)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(188, 211, 13));
        jLabel5.setText("MOBILE NUMBER");

        jTextField5.setFont(new java.awt.Font("Nirmala UI Semilight", 1, 13)); // NOI18N

        jLabel6.setFont(new java.awt.Font("Myanmar Text", 1, 13)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(188, 211, 13));
        jLabel6.setText("TARIFF / DAY");

        jLabel7.setFont(new java.awt.Font("Myanmar Text", 1, 13)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(188, 211, 13));
        jLabel7.setText("NO. OF DAYS STAY");

        jLabel8.setFont(new java.awt.Font("Myanmar Text", 1, 13)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(188, 211, 13));
        jLabel8.setText("TOTAL TARIFF");

        jLabel9.setFont(new java.awt.Font("Myanmar Text", 1, 13)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(188, 211, 13));
        jLabel9.setText("EMAIL");

        jTextField6.setFont(new java.awt.Font("Nirmala UI Semilight", 1, 13)); // NOI18N

        jTextField7.setFont(new java.awt.Font("Nirmala UI Semilight", 1, 13)); // NOI18N

        jTextField8.setFont(new java.awt.Font("Nirmala UI Semilight", 1, 13)); // NOI18N

        jTextField9.setFont(new java.awt.Font("Nirmala UI Semilight", 1, 13)); // NOI18N

        jButton2.setBackground(new java.awt.Color(84, 159, 232));
        jButton2.setFont(new java.awt.Font("Myanmar Text", 1, 12)); // NOI18N
        jButton2.setForeground(new java.awt.Color(31, 24, 27));
        jButton2.setText("CHECK-OUT");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jButton3.setBackground(new java.awt.Color(84, 159, 232));
        jButton3.setFont(new java.awt.Font("Myanmar Text", 1, 12)); // NOI18N
        jButton3.setForeground(new java.awt.Color(31, 24, 27));
        jButton3.setText("RESET");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jButton2)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                    .addComponent(jTextField6, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 272, Short.MAX_VALUE)
                                    .addComponent(jLabel2, javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jTextField2, javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel6, javax.swing.GroupLayout.Alignment.LEADING))
                                .addGap(101, 101, 101)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(jTextField3, javax.swing.GroupLayout.DEFAULT_SIZE, 222, Short.MAX_VALUE)
                                    .addComponent(jLabel3)
                                    .addComponent(jLabel7)
                                    .addComponent(jTextField7))))
                        .addGap(87, 87, 87)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(jLabel4)
                                    .addComponent(jTextField4, javax.swing.GroupLayout.DEFAULT_SIZE, 226, Short.MAX_VALUE)
                                    .addComponent(jTextField8)
                                    .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 97, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 70, Short.MAX_VALUE)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(jLabel5)
                                    .addComponent(jTextField5, javax.swing.GroupLayout.DEFAULT_SIZE, 236, Short.MAX_VALUE)
                                    .addComponent(jLabel9)
                                    .addComponent(jTextField9))
                                .addGap(36, 36, 36))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jButton3, javax.swing.GroupLayout.PREFERRED_SIZE, 89, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(0, 0, Short.MAX_VALUE)))))
                .addContainerGap())
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(492, Short.MAX_VALUE)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, 144, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 105, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(437, 437, 437))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel1)))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(jLabel3)
                    .addComponent(jLabel4)
                    .addComponent(jLabel5))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextField2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextField3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextField4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextField5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(48, 48, 48)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(jLabel7)
                    .addComponent(jLabel8)
                    .addComponent(jLabel9))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextField6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextField7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextField8, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextField9, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 28, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jButton3)
                    .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 294, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 160, 1270, 620));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void formComponentShown(java.awt.event.ComponentEvent evt) {//GEN-FIRST:event_formComponentShown
        // TODO add your handling code here:
        ResultSet r = select.getData("select * from custdetail where checkout is null ORDER BY GET_ID ASC ");
        DefaultTableModel model=(DefaultTableModel)jTable1.getModel();
        try
        {
            while(r.next())
            {
                   model.addRow(new Object[]{r.getString(1),r.getString(2),r.getString(3),r.getString(4),r.getString(5),r.getString(6),r.getString(7),r.getString(8),r.getString(9),r.getString(10),r.getString(11),r.getString(12),r.getString(13),r.getString(14),r.getString(15),r.getString(16),r.getString(18),r.getString(19)});
            }
            r.close();
        }
        catch(Exception e)
        {
            JOptionPane.showMessageDialog(null, "");
        }
    }//GEN-LAST:event_formComponentShown

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        String roomno=jTextField1.getText();
        try
        {
            ResultSet r = select.getData("select * from custdetail where room_no='"+roomno+"' and checkout is NULL");
            if(r.next())
            {
                jTextField1.setEditable(false);
                get_id=r.getInt(1);
                jTextField2.setText(r.getString(2));
                jTextField3.setText(r.getString(11));
                jTextField5.setText(r.getString(3));
                jTextField6.setText(r.getString(16));
                jTextField9.setText(r.getString(5));
                address = r.getString(9);
                member  = r.getString(10);
                roomtype = r.getString(13);
                totamt = r.getString(18);
               SimpleDateFormat my = new SimpleDateFormat("dd-MM-yyyy");
               Calendar cal = Calendar.getInstance();
               jTextField4.setText(my.format(cal.getTime()));
               String datebeforeS = r.getString(11);
               java.util.Date datebefore = my.parse(datebeforeS);
               String dateafterS = my.format(cal.getTime());
               java.util.Date dateafter = my.parse(dateafterS);
               long diff = dateafter.getTime()-datebefore.getTime();
               int nod = (int)(diff/(1000*60*60*24));
               if(nod == 0)
                   nod = 1;
               jTextField7.setText(String.valueOf(nod));
               double price = Double.parseDouble(jTextField6.getText());
               jTextField8.setText(String.valueOf(nod*price));
               roomtype = r.getString(13);
               bed = r.getString(12);
               double con =  Double.parseDouble(jTextField8.getText());
               gst = (con * 9)/100;
            }
            else
                JOptionPane.showMessageDialog(null,"Room Number Does'nt Exist");
        }
        catch(Exception e)
        {
            JOptionPane.showMessageDialog(null, e);
        }
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        String name= jTextField2.getText();
        String mobile= jTextField5.getText();
        String email = jTextField9.getText();
        
        String checkout = jTextField4.getText();
        String nod = jTextField7.getText();
        String ta = jTextField8.getText();
        roomno = jTextField1.getText();
        Query = "update custdetail set total_days='"+nod+"',total_amt='"+ta+"',checkout='"+checkout+"' where get_id='"+get_id+"'";
        IUD.setData(Query, "Customer Profile Updated");
        
        Query = "update manageroom set status='NOT BOOKED' where room_no='"+roomno+"'";        
        IUD.setData(Query, "Thank You For Choosing Us. Hope To See You Soon");
        
        
        String path="E:\\";
        com.itextpdf.text.Document doc = new com.itextpdf.text.Document();
      
      
            
            try
            {
                PdfWriter.getInstance(doc, new FileOutputStream(path+""+get_id+".pdf"));
                doc.open();
                
                
                Font f1 = new Font(Font.FontFamily.TIMES_ROMAN,22,Font.BOLD);
                Paragraph a = new Paragraph("THE GOLDEN LEAF RETREAT",f1);
                a.setAlignment(Element.ALIGN_CENTER);
                doc.add(a);
                
                Font f2 = new Font(Font.FontFamily.TIMES_ROMAN,9,Font.NORMAL);
                Paragraph b = new Paragraph("ADDRESS: Mashobra, Himachal Pradesh 171007",f2);
                b.setAlignment(Element.ALIGN_CENTER);
                doc.add(b);
                
                Paragraph c = new Paragraph("PHONE: 17728XXXXXXXX",f2);
                c.setAlignment(Element.ALIGN_CENTER);
                doc.add(c);
                
                Paragraph d = new Paragraph("Email: test@gmail.com\nCountry: INDIA\nGST Number: 19XXXXXXXXXXXXX",f2);
                d.setAlignment(Element.ALIGN_CENTER);
                doc.add(d);
                
                
                Paragraph e = new Paragraph("             ");
                doc.add(e);               
                
                
                Font f3 = new Font(Font.FontFamily.HELVETICA,8);
                
                PdfPTable pdfPTable = new PdfPTable(2); 
                PdfPCell pdfPCell1 = new PdfPCell(new Paragraph("Customer Name: "+name+"\n"+"\nAddress: "+address+"\n"+"\nPlan: CP"+"\n"+"\nPax: "+member+"\n"+"\nArr. Date: "+jTextField3.getText()+"\n",f3));
                PdfPCell pdfPCell2 = new PdfPCell(new Paragraph("Invoice No: "+get_id+"\n"+"\nInvoice Date: "+jTextField4.getText()+"\n"+"\nRoom No: "+roomno+"\n"+"\nRoom Type: "+roomtype+"\n"+"\nDep. Date: "+jTextField4.getText()+"\n",f3));  
                pdfPTable.addCell(pdfPCell1);
                pdfPTable.addCell(pdfPCell2);       
                doc.add(pdfPTable);
                
                Font f4 = new Font(Font.FontFamily.TIMES_ROMAN,10,Font.BOLD);
                PdfPTable pdfPTable1 = new PdfPTable(1);
                PdfPCell pdfPCell3 = new PdfPCell(new Paragraph("                                                                      Payment Details ",f4));
                pdfPTable1.addCell(pdfPCell3);
                doc.add(pdfPTable1);
                
                
                PdfPTable pdfPTable2 = new PdfPTable(2);
                PdfPCell pdfPCell4 = new PdfPCell(new Paragraph("Accommodation Charge\n\nNo.of Days Stay\n\nCGST (9% incl.) \n\nSGST (9% incl.) ",f3));
                PdfPCell pdfPCell5 = new PdfPCell(new Paragraph(jTextField6.getText()+"\n\n"+jTextField7.getText()+"\n\n"+gst+"\n\n"+gst+"\n\n",f3));
                pdfPTable2.addCell(pdfPCell4);
                pdfPTable2.addCell(pdfPCell5);
                doc.add(pdfPTable2);

                PdfPTable pdfPTable5 = new PdfPTable(2);
                PdfPCell pdfPCell9 = new PdfPCell(new Paragraph("\nGrand Total\n",f3));
                PdfPCell pdfPCell10 = new PdfPCell(new Paragraph("\n"+jTextField8.getText()+"\n",f3));
                pdfPTable5.addCell(pdfPCell9);
                pdfPTable5.addCell(pdfPCell10);
                doc.add(pdfPTable5);
                
                Font f5 = new Font(Font.FontFamily.TIMES_ROMAN,9,Font.BOLD);
                PdfPTable pdfPTable3 = new PdfPTable(1);
                PdfPCell pdfPCell6 = new PdfPCell(new Paragraph("\nThis is a computer generated invoice and does not require Signature/Stamp\n",f5));
                pdfPTable3.addCell(pdfPCell6);
                doc.add(pdfPTable3);

                PdfPTable pdfPTable4 = new PdfPTable(1);

                PdfPCell pdfPCell8 = new PdfPCell(new Paragraph("\n\nGUEST SIGNATURE                                                                                                    CASHIER SIGNATURE",f5));

                pdfPTable4.addCell(pdfPCell8);
                doc.add(pdfPTable4);
                
                
            }
            catch(Exception e)
            {
                JOptionPane.showMessageDialog(null, "");
            }             
            doc.close();
            int a = JOptionPane.showConfirmDialog(null, "Do You Want To Print Bill","Select",JOptionPane.YES_NO_OPTION);
            if(a==0)
            {
                try
                {
                    if((new File("E:\\"+get_id+".pdf")).exists())
                    {
                        Process p = Runtime
                                .getRuntime()
                                .exec("rundll32 url.dll FileProtocolHandler E:\\"+get_id+".pdf");
                    }
                    else
                    {
                        JOptionPane.showMessageDialog(null,"File Does not Exists");
                    }
                }
                catch(Exception e)
                {
                    JOptionPane.showMessageDialog(null, "");
                }   
                
            }     
            setVisible(false);
            new checkout().setVisible(true);
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        // TODO add your handling code here:
        jTextField1.setText(" ");
        jTextField2.setText(" ");
        jTextField3.setText(" ");
        jTextField4.setText(" ");
        jTextField5.setText(" ");
        jTextField6.setText(" ");
        jTextField7.setText(" ");
        jTextField8.setText(" ");
        setVisible(false);
        new checkout().setVisible(true);
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
        // TODO add your handling code here:
        setVisible(false);
        new home().setVisible(true);
    }//GEN-LAST:event_jButton5ActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        // TODO add your handling code here:
        int x = JOptionPane.showConfirmDialog(null, "Confirm","Select",JOptionPane.YES_NO_OPTION);
        if(x==0)
        System.exit(0);
    }//GEN-LAST:event_jButton4ActionPerformed

    private void jTable1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTable1MouseClicked
        // TODO add your handling code here:
        boolean a = jTable1.isEditing();
        if(a==false)
              JOptionPane.showMessageDialog(null,"Editing Table is Not Possible!!! Sorry");
    }//GEN-LAST:event_jTable1MouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(checkout.class.getName()).log(java.util.logging.Level.FINER, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(checkout.class.getName()).log(java.util.logging.Level.FINER, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(checkout.class.getName()).log(java.util.logging.Level.FINER, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(checkout.class.getName()).log(java.util.logging.Level.FINER, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new checkout().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField jTextField2;
    private javax.swing.JTextField jTextField3;
    private javax.swing.JTextField jTextField4;
    private javax.swing.JTextField jTextField5;
    private javax.swing.JTextField jTextField6;
    private javax.swing.JTextField jTextField7;
    private javax.swing.JTextField jTextField8;
    private javax.swing.JTextField jTextField9;
    // End of variables declaration//GEN-END:variables
}
